function net = EncDecConv(imageSize,numClasses)
% Encoder-Decoder
encdecLayers = segnetLayers(imageSize,32,4,NumConvolutionLayers=1,NumOutputChannels=[64 128 256 512]);
encdecLayers = removeLayers(encdecLayers,{'softmax','pixelLabels'});
regrLayers = [convolution2dLayer(1,imageSize(3),Padding="same",Name="convout"), ...
              batchNormalizationLayer, ...
              clippedReluLayer(1.0,Name="cliprelu")];
encdecLayers = addLayers(encdecLayers,regrLayers);
encdecLayers = connectLayers(encdecLayers,"decoder1_relu_","convout");
% Classification network
blk1 = [convolution2dLayer(1,32,Padding="same"),...
        batchNormalizationLayer, ...
        reluLayer, ...
        maxPooling2dLayer(8,'Stride',8)];

blk2 = [convolution2dLayer(1,64,Padding="same"),...
        batchNormalizationLayer, ...
        reluLayer, ...
        maxPooling2dLayer(4,'Stride',4)];

blk3 = [convolution2dLayer(1,128,Padding="same"),...
        batchNormalizationLayer, ...
        reluLayer, ...
        maxPooling2dLayer(2,'Stride',2)];

blk4 = [convolution2dLayer(1,256,Padding="same"),...
        batchNormalizationLayer, ...
        reluLayer];

classLayer = [depthConcatenationLayer(4), ...
              convolution2dLayer(3,960,Padding="same"), ...
              batchNormalizationLayer, ...
              reluLayer, ...
              globalAveragePooling2dLayer, ...
              fullyConnectedLayer(numClasses), ...
              softmaxLayer];

encdecLayers = addLayers(encdecLayers,blk1);
encdecLayers = addLayers(encdecLayers,blk2);
encdecLayers = addLayers(encdecLayers,blk3);
encdecLayers = addLayers(encdecLayers,blk4);
encdecLayers = addLayers(encdecLayers,classLayer);

encdecLayers = connectLayers(encdecLayers,"encoder1_maxpool/out","conv");
encdecLayers = connectLayers(encdecLayers,"encoder2_maxpool/out","conv_1");
encdecLayers = connectLayers(encdecLayers,"encoder3_maxpool/out","conv_2");
encdecLayers = connectLayers(encdecLayers,"encoder4_maxpool/out","conv_3");

encdecLayers = connectLayers(encdecLayers,"maxpool","concat/in1");
encdecLayers = connectLayers(encdecLayers,"maxpool_1","concat/in2");
encdecLayers = connectLayers(encdecLayers,"maxpool_2","concat/in3");
encdecLayers = connectLayers(encdecLayers,"relu_3","concat/in4");

net = dlnetwork(encdecLayers);